/*******************************************************************************
* File Name: gatt.h
*
* Description: This file is the public interface of gatt.c
*
* Related Document: See README.md
*
********************************************************************************
* Copyright 2024-2025, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/
#ifndef APP_GATTS_H__
#define APP_GATTS_H__

/*******************************************************************************
* Includes
*******************************************************************************/
#include "wiced_bt_gatt.h"
#include "wiced_bt_ble.h"
#include "cycfg_gatt_db.h"  /* generated by BT configurator */

/*******************************************************************************
* Function Declarations
*******************************************************************************/
 wiced_bt_gatt_status_t gatt_read_req_default_handler( uint16_t conn_id,
 wiced_bt_gatt_read_t *p_req,wiced_bt_gatt_opcode_t opcode,
 uint16_t len_requested );
 wiced_bt_gatt_status_t gatt_write_default_handler(uint16_t conn_id,
         wiced_bt_gatt_write_req_t * p_wr_data);
 wiced_bt_gatt_status_t gatt_initialize(void);
const gatt_db_lookup_table_t * wiced_bt_util_get_attribute
(gatt_db_lookup_table_t * p_attribute, uint16_t handle);

#endif //APP_GATTS_H__
